"""Skill registry — extracted from app_server.py."""

SKILL_REGISTRY = {
    "knowledge-extraction": {
        "id": "knowledge-extraction",
        "name": "知识萃取",
        "version": "3.0.0",
        "description": "基于场景骨架和知识文档，通过LLM生成 Agent SKILL.md 初稿。",
        "prompt_template": "step2_generate_skill_md.txt",
        "related_step": 2,
        "enabled": True,
        "detailed_description": "知识萃取是隐性知识显性化流水线的核心入口。该 Skill 接收 Step1 生成的场景骨架（含业务领域、客户画像、营销目标）以及专家提供的知识文档（制度文件、案例复盘、培训材料等），调用大语言模型从中提炼出结构化的 Agent SKILL.md。\n\nSKILL.md 包含角色定位、核心流程、判断规则、数据取数逻辑等要素，是后续步骤的输入基础。",
        "business_value": "将散落在文档、制度、案例中的专家经验转化为机器可执行的 Agent Skill，大幅降低知识沉淀的人力成本。一次萃取可覆盖一个完整业务场景，后续通过流水线持续迭代。",
        "usage_guide": "1. 确保 Step1 场景锚定已完成，场景骨架已生成\n2. 准备知识文档（支持 .txt / .docx / .pdf，也可直接粘贴文本）\n3. 在界面中选择「Markdown 流水线」模式\n4. 选择模型后点击「执行知识萃取」\n5. 等待 LLM 生成 SKILL.md 初稿，预览并确认",
        "input_example": "场景：对公普惠客户潜力营销\n知识文档：科技型企业普惠贷款营销知识文档.txt（含客户筛选规则、数据标签、决策建议）",
        "output_example": "SKILL.md 文件，包含：角色定义（你是一名对公客户经理）、核心流程（客户筛选→需求分析→产品匹配→营销执行）、数据表引用（对公客户信息表、存款信息表等）、判断规则（准入条件、资质标签等）",
        "applicable_scenarios": ["对公客户潜力挖掘与营销", "普惠贷款产品推荐", "客户分层与精准营销", "新客户准入评估"],
        "capabilities": ["场景骨架解析", "知识文档理解", "规则与逻辑提炼", "Agent SKILL.md 生成"],
        "supported_formats": [".txt", ".docx", ".pdf", "纯文本粘贴"],
        "output_styles": ["结构化 SKILL.md", "含角色/流程/规则/数据"],
        "triggers": ["用户完成 Step1 场景锚定后", "用户上传知识文档并选择【知识萃取】"],
        "limitations": ["依赖输入的文档质量，文档信息不足时产出可能不完整", "LLM 生成的初稿需要专家在 Step3 对齐确认", "暂不支持图片/表格结构文档的深度解析"],
    },
    "knowledge-revision": {
        "id": "knowledge-revision",
        "name": "知识对齐",
        "version": "3.0.0",
        "description": "基于专家自然语言反馈，通过LLM对 SKILL.md 进行修订对齐。",
        "prompt_template": "step3_align_with_expert.txt",
        "related_step": 3,
        "enabled": True,
        "detailed_description": "知识对齐是专家介入修订的核心环节。该 Skill 接收 Step2 生成的 SKILL.md 初稿，结合专家的自然语言反馈意见（如「客户筛选条件需要增加成立年限判断」「额度测算逻辑不对，参照 XX 制度」），调用 LLM 进行语义级修订并生成新版 SKILL.md。\n\n支持多轮修订：每轮反馈独立生成一个修订版本，不覆盖历史，专家可在界面中预览差异。",
        "business_value": "解决 LLM 初稿与专家实际经验之间的偏差。通过自然语言交互而非手动编辑，将专家的隐性判断（「正常情况怎么处理」「边界条件是什么」）快速融入知识体系，确保产出符合业务实际。",
        "usage_guide": "1. 查看 Step2 生成的 SKILL.md 初稿内容\n2. 在「专家反馈」输入框中用自然语言描述需要修改的内容\n3. 选择模型后点击「发送并智能修订」\n4. 预览修订后的 SKILL.md，如不满意可继续反馈\n5. 确认无误后进入 Step4",
        "input_example": "专家反馈：「客户筛选部分，科技型企业还要区分是否有有效专利，没有专利的即使有资质标签也不应该优先营销。在额度测算部分，补充一条规则：如果客户有他行信用贷款且正常还款，可以适度上浮额度。」",
        "output_example": "修订版 SKILL.md，在原文基础上：1) 客户筛选规则新增「有效专利判断」条件分支；2) 额度测算部分新增「他行信用贷款正常还款」上浮规则；3) 逻辑前后保持一致性",
        "applicable_scenarios": ["LLM 初稿需要领域专家审核修订", "业务规则或制度发生变更需要更新逻辑", "多轮迭代优化的知识条目"],
        "capabilities": ["自然语言反馈理解", "SKILL.md 语义级修订", "多轮修订版本管理", "修订日志与差异追踪"],
        "supported_formats": ["SKILL.md 全文修订"],
        "output_styles": ["修订版 SKILL.md", "含修订记录元信息"],
        "triggers": ["Step2 知识萃取完成", "专家在 Step3 界面提交反馈"],
        "limitations": ["单次反馈建议聚焦于一个方面，避免多主题混杂降低修订质量", "修改幅度受 LLM 上下文窗口限制（max_tokens=100000）", "无法保证自动验证修订逻辑的正确性，需专家人工确认"],
    },
    "skill-generator": {
        "id": "skill-generator",
        "name": "Skill生成器",
        "version": "1.0.0",
        "description": "基于修订后的 SKILL.md，通过LLM生成 QA对、思维链和待验证 Agent-Skill。",
        "prompt_template": "step4_build_deliverables.txt",
        "related_step": 4,
        "enabled": True,
        "detailed_description": "Skill生成器是流水线的交付环节，将经过专家确认的 SKILL.md 转化为可直接分发的 Agent Skill 包。\n\n输出包含三部分：1) QA 对（Question-Answer 验证用例，用于评估 Skill 准确率）；2) 思维链（Chain-of-Thought，对核心判断逻辑的分步推演）；3) Agent-Skill 可执行包（含 SKILL.md、manifest.json、执行脚本等的 zip 压缩包，符合 agentskills.io 标准）。\n\n生成的 Agent-Skill 可在 Step5 中进行 P/R/F1 验证，通过后产生最终发布的 Skill zip。",
        "business_value": "从人工知识到可分发、可执行的 Agent Skill 的一键打包。生成的 QA 对可直接用于后续回归测试，思维链帮助新用户理解模型判断逻辑，zip 包可通过内网或平台分发给一线客户经理使用。",
        "usage_guide": "1. 确保 Step3 知识对齐已完成，SKILL.md 已确认\n2. 在 Step4 界面选择「构建 Skill」\n3. 等待 LLM 生成三份交付物：QA 对、CoT、Agent-Skill zip\n4. 预览 QA 对和思维链内容\n5. 进入 Step5 进行验证回放",
        "input_example": "输入：经 Step3 专家确认的对公普惠客户潜力营销 SKILL.md（含客户筛选规则、额度测算逻辑、产品推荐策略等完整内容）",
        "output_example": "输出三份文件：1) qa_*.json — 约 10-20 组 QA 对，覆盖准入判断、产品推荐、拒贷理由等场景；2) cot_*.md — 分步思维链，展示从客户信息到营销建议的完整推理路径；3) SKILL_VERIFY_*.zip — 可部署的 Agent Skill 包",
        "applicable_scenarios": ["SKILL.md 定稿后生成可交付 Skill", "需要 QA 验证数据集", "需要 Chain-of-Thought 解释逻辑"],
        "capabilities": ["SKILL.md 解析与重构", "QA 验证集自动生成", "Chain-of-Thought 推理链生成", "Agent-Skill zip 打包"],
        "supported_formats": ["SKILL.md → QA JSON + CoT Markdown + Skill zip"],
        "output_styles": ["结构化 QA 对", "Markdown 思维链", "agentskills.io 标准 zip"],
        "triggers": ["Step3 知识对齐完成并确认"],
        "limitations": ["QA 对的覆盖面和准确性受 SKILL.md 完整度影响", "思维链为 LLM 推导，可能存在推理盲区", "zip 包生成后需在 Step5 通过 P/R/F1 验证才能发布"],
    },
}
